### ISSUE TITLE
Add additional distribution strategies to AI Proxy

### ISSUE THREAD

**Issue by iMicknl** [Azure/enterprise-azureai#22]
Currently a round-robin strategy is used for the AI Proxy. Would be great to have multiple options here.

- Priority based 
	- For example use your provisioned-managed capacity (PTU) first, and only fail-over to pay as you go, or prefer regions closest to the application first and fail-over to other regions
	- PTU deployments use different HTTP headers that show usage and retry-after time

**Comment by iMicknl** [comment]
Would be good to make this configurable. Perhaps via [JSON values that we inject to the AppConfiguration?](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-leverage-json-content-type#create-json-key-values-using-azure-portal)

A JSON could look like this:
```jsonc
[
    {
        "deployment-name": "gpt-35-turbo",
        "distribution-strategy": "priority", // or "random", "priority"
        "endpoints": [
            {
                "endpoint": "https://cog-d7knihn7w73zw-swedencentral.openai.azure.com",
                "deployment_name": "gpt-35-turbo-ptu", // optional (if different name)
                "priority": 1
            },
            {
                "endpoint": "https://cog-d7knihn7w73zw-swedencentral.openai.azure.com",
                "priority": 2
            }
        ]
    },
    {
        "deployment-name": "text-embeddings-ada-002",
        "distribution-strategy": "round-robin", // or "random", "priority"
        "endpoints": [
            {
                "endpoint": "https://cog-d7knihn7w73zw-swedencentral.openai.azure.com",
            },
            {
                "endpoint": "https://cog-d7knihn7w73zw-swedencentral.openai.azure.com",
                "deployment_name": "text-embeddings-ada" // optional (if different name)
            }
        ]
    }
]
```

Other repositories use a YAML for this: https://github.com/timoklimmer/powerproxy-aoai/blob/main/config/config.example.yaml, and this allows us to load a more advanced config. Pulling this from the API of available models, because you might want to have a more advanced workflow.

**Comment by azureholic** [comment]
feature/smartlb PR should implement this
