### ISSUE TITLE
Migrate Azure API Management instance to stv2 platform

### ISSUE THREAD

**Issue by iMicknl** [Azure/enterprise-azureai#29]
[Azure API Management - stv1 platform retirement (August 2024) | Microsoft Learn](https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/stv1-platform-retirement-august-2024?WT.mc_id=Portal-Microsoft_Azure_Expert)

[Migrate Azure API Management instance to stv2 platform | Microsoft Learn](https://learn.microsoft.com/en-us/azure/api-management/migrate-stv1-to-stv2?tabs=portal)

**Comment by azureholic** [comment]
fix is in my fork...next PR will include it
