### ISSUE TITLE
Fail to run the command `azd up`

### ISSUE THREAD

**Issue by jerryshia** [Azure/enterprise-azureai#42]
**Describe the issue:**
Fail to run the command `azd up`  and there is an error: "deploy 'openai-secondary' fail".

![image](https://github.com/Azure/enterprise-azureai/assets/139106314/c1c0a2e1-df81-444d-a84b-8642e89d3f20)

**Repro Steps:**

1. Run `azd init -t Azure/enterprise-azureai`.
2. Run `azd env set USE_REDIS_CACHE_APIM 'true'`.
3. Run `azd env set SECONDARY_OPENAI_LOCATION 'eastus'`.
4. Run `azd up` .

**Expected behavior:**
Run `azd up`  successfully.
@pascalvanderheiden and @hemarina for notification.

**Comment by azureholic** [comment]
in .env of your environment
MY_IP_ADDRESS should be an IPv4 address. This is used to give your local machine access to the container registry for pushing the container image.

It also looks like the subscription you are targeting does not have quota for Azure OpenAI instances

**Comment by pascalvanderheiden** [comment]
@jerryshia Can you try again, taking into account the comment mentioned above by @azureholic?

**Comment by azureholic** [comment]
agree. This is only needed for azd to push the container to the container registry from a local workstation. The ACR firewall does not support IPv6 adresses. We should mention this in the docs.
