### ISSUE TITLE
[Question] Streaming support

### ISSUE THREAD

**Issue by codylittle** [Azure/enterprise-azureai#59]
Under the [Key Features](https://github.com/Azure/enterprise-azureai?tab=readme-ov-file#key-features), it outlines that streaming requests are supported for all features.

However, after reading the [APIM policy](https://github.com/Azure/enterprise-azureai/blob/main/infra/modules/apim/policies/api_policy_openai.xml#L17), it reads as if streaming requests are blocked.

I'm yet to deploy this, so forgive me if this is just "APIM Magic".
But, are streaming completions actually supported?

**Comment by azureholic** [comment]
Hi @codylittle 
It is supported. The policy you mention is not used in the deployment (nice find though!)
The policy that is used is the api-policy-chargeback.xml that uses the proxy. That proxy supports streaming and token calculation for streaming.

**Comment by codylittle** [comment]
Thanks @azureholic for the quick response - looking forward to setting this up
